LandingPage/urls.py
from django.urls import path
from . import views

app_name = 'LandingPage'

urlpatterns = [
    path('', views.landing_page, name='landing_page'),
    path('add_status/', views.add_status, name='add_status')
]

StoryDelapan/urls.py
from django.urls import path
from .views import *

app_name = 'StoryDelapan'

urlpatterns = [
    path('', index, name='index'),
    path('cari/<str:param>/', cari, name='cari'),
]

StoryEnam/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('LandingPage.urls',namespace='LandingPage')),
    path('storyTujuh/', include('StoryTujuh.urls',namespace='StoryTujuh')),
    path('storyDelapan/', include('StoryDelapan.urls',namespace='StoryDelapan')),
    path('storySembilan/', include('StorySembilan.urls',namespace='StorySembilan'))
]

StorySembilan/urls.py
from django.urls import path, include
from .views import story_sembilan_page, funct_login, funct_logout

app_name="Story9"
urlpatterns = [
    path('', story_sembilan_page, name="story9"),
    path('login/', funct_login, name="login"),
    path('logout/', funct_logout, name="logout")
]

StoryTujuh/urls.py
from django.urls import path
from .views import story_tujuh_page

app_name = 'StoryTujuh'

urlpatterns = [
    path('', story_tujuh_page, name="story_tujuh_page")
]

LandingPage/models.py
from django.db import models
from django.utils import timezone

# Create your models here.

class Status(models.Model):
    status = models.CharField(max_length=300)
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.status

StoryDelapan/models.py
from django.db import models

# Create your models here.

StorySembilan/models.py
from django.db import models

# Create your models here.

StoryTujuh/models.py
from django.db import models

# Create your models here.

LandingPage/forms.py
from django import forms

class StatusForm(forms.Form):
    status = forms.CharField(max_length=300)

StoryDelapan/forms.py
from django import forms

class SearchBar (forms.Form):
    query = forms.CharField(min_length=1)

LandingPage/views.py
from django.shortcuts import render, redirect
from .models import Status
from .forms import StatusForm

# Create your views here.
def landing_page(request):
    status = Status.objects.all().values()
    context = {
        'form' : StatusForm,
        'status' : status
    }
    return render(request, 'landing.html', context)

def add_status(request):
    if StatusForm(request.POST).is_valid():
        new_status = Status.objects.create(status=request.POST['status'])
    return redirect('/')

StoryDelapan/views.py
from django.shortcuts import render
from django.http import JsonResponse
import requests
import json
from .forms import SearchBar


# Create your views here.

def index(request):
    context = {
        'form' : SearchBar()
    }
    return render(request, 'StoryDelapan.html', context)

def cari(request, param):
    json = requests.get("https://www.googleapis.com/books/v1/volumes?q=" + param).json()
    return JsonResponse(json)

StorySembilan/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout
from django.contrib.auth.decorators import login_required

def story_sembilan_page(request):
    return render(request, "storysembilan.html")

def funct_login(request):
    if request.method == "POST":
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            return redirect('/storySembilan')
    else:
        form = AuthenticationForm()
    return render(request, 'login.html', {'form': form})

def funct_logout(request):
    logout(request)
    return redirect('/storySembilan')

StoryTujuh/views.py
from django.shortcuts import render
from django.http import HttpResponse

def story_tujuh_page(request):
    return render(request, 'storytujuh.html')

LandingPage/templates/landing.html
<!DOCTYPE html>
{% load static %}
<html>
    <head>
        <title>Story 6</title>
        <meta charset="utf-8">
    </head>
    <body>
        <p>
            <form action="{% url 'LandingPage:add_status' %}" method="POST">
                <table style="margin:auto">
                    {% csrf_token %}
                    {{form.as_table}}
                </table>
                <button type="submit" style="margin-top: 10px">Submit</button>
            </form>
        </p>
        <p>
            <table class="table">
                <thead>
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">Status</th>
                        <th scope="col">Date</th>
                    </tr>
                </thead>
                <tbody>
                    {% for stat in status %}
                    <tr>
                        <th scope="row">{{forloop.counter}}</th>
                        <td>{{stat.status}}</td>
                        <td>{{stat.date}}</td>
                    {% endfor %}
                    </tr>
                </tbody>
            </table>
        </p>
    </body>
</html>

StoryDelapan/templates/StoryDelapan.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Story 8</title>
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
      integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"
      crossorigin="anonymous"
    />

  </head>
  <body>
    <form id="search-bar" name="search-bar" action="" method="GET">
      {% csrf_token %} {{form}}
      <input type="submit" value="submit" />
    </form>
    <table>
        <thead>
            <tr>
                <th scope="col-3">image</th>
                <th scope="col-3">Title</th>
                <th scope="col-3">Author</th>
            </tr>
        </thead>
        <tbody class="body"></tbody>
    </table>
    <script
      src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
      integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
      integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
      integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
      crossorigin="anonymous"
    ></script>
    <script src="{% static 'js/cari.js'%}"></script>
  </body>
</html>

StorySembilan/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Story 9</title>
</head>
<body>
<div style="display:flex;justify-content:center">
    <form class="auth-form" action="{% url 'StorySembilan:login' %}" method="POST">
        {% csrf_token %}
        <label for="id_username">Username:</label>
        <input type="text" name="username" autofocus="" required="" id="id_username">
        <label for="id_password">Password:</label>
        <input type="password" name="password" required="" id="id_password">
        {% if request.GET.next %}
            <input type="hidden" name="next" value="{{ request.GET.next }}">
        {% endif %}
        <input type="submit" id="login" value="Login">
    </form>
</div>
</body>
</html>

StorySembilan/templates/storysembilan.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Story 9</title>
</head>
<body>
    <div style="display:flex;justify-content:center">
        {% if user.is_authenticated %}
        <h1>Selamat Datang, {{ user }}</h1>
        <a href="{% url 'StorySembilan:logout' %}">
            <button id="logout">Logout</button>
        </a>
        {% else %}
        <h1>
            Tolong Login
        </h1>
        <a href="{% url 'StorySembilan:login' %}">
                <button id="login">Login</button>
        </a>
        {% endif %}
    </div>
</body>
</html>

StoryTujuh/templates/storytujuh.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">

        <link rel="stylesheet" href="/static/css/bootstrap.css">
        <link rel="stylesheet" href="/static/css/storyTujuh.css">
        <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
        <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
        <title>Story 7</title>
    </head>
    <body class="row vertical-center-row">
        <div class="col-4">
            <div class=container id="accordion">
                <button class="accordion" >Aktivitas</button>
                <div class="panel">
                    <p>Gantiin staff yang tiba-tiba keracunan makanan</p>
                </div>
                
                <button class="accordion">Pengalaman</button>
                <div class="panel">
                    <p>Dokum dimana-mana</p>
                </div>
                
                <button class="accordion">Pencapaian?</button>
                <div class="panel">
                    <p>Pertanyaan menarik</p>
                </div> 
            </div>
            
            <div class="container">
                <h5 id="theme">Ganti Warna</h5>
                <button class="btn" name="lightmode" onclick="UbahTerang()">Terang</button>
                <button class="btn" name="darkmode" onclick="UbahGelap()">Gelap</button>

            </div>
        </div>

        <script>
             $( function() {
                $( "#accordion" ).accordion({active: false, collapsible: true});
            });

            function UbahTerang(){
            $('body').css('background-color', 'whitesmoke'); 
            $('.accordion').css('background-color', 'black');  
            $('.panel').css('background-color', 'white');
            $('#theme').css('color', 'black');
        }
        function UbahGelap(){
            $('body').css('background-color', 'black');
            $('.accordion').css('background-color', 'grey');    
            $('.panel').css('background-color', 'whitesmoke');
            $('#theme').css('color', 'white');   
        }
        </script>

    </body>
</html>